### PR TITLE
Fix off by one error

### PR DESCRIPTION
**Pull request by m-novikov**
Looks like this was the cause of segfault

### CODE REVIEW

**Comment by constantinpape** [comment]
Thanks!
I have no idea how the one off in the out-of-range check caused the weird seg-fault behaviour I have seen, but it's probably the cause. Will check later.

I hadn't tested the `ravel_from_strides` yet, that one was pretty obvious ...

**Comment by constantinpape** [comment]
Come to think of it, it does make a bit of sense.
The seg-fault occured when a value read from invalid memory was passed to `pq.emplace`.
Still don't get why it didn't seg-fault when compiled with `Debug` though.

**Comment by m-novikov** [comment]
It's passed by reference
https://github.com/m-novikov/nifty/blob/d53073e3cdb6df64df07a047c20a0097845ba4b6/include/nifty/skeletons/helper.hxx#L141
To `emplace` call, so on creation of entry to priority queue, it tries to use comparator and derefences pointer outside.
In debug it's probably less tightly packed.

**Comment by constantinpape** [comment]
> To `emplace` call, so on creation of entry to priority queue, it tries to use comparator and derefences pointer outside.

Yep, just figured that out too ^^.


> In debug it's probably less tightly packed.

Makes sense.

**Pull request merged**
